name: Docker Image CI

on:
  schedule:
    - cron: "9 * * * *"
  push:
    branches: [ "DISABLED-main" ]
  pull_request:
    branches: [ "DISABLED-main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag github-repo-utility:latest
