# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go
env:
  binary: github-utility
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'release'
  schedule:
    - cron: "00 06 * * 6"
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: CGO_ENABLED=0 go build -ldflags="-s -w" -o $binary -v ./... && chmod +x $binary && sha256sum $binary && ls -al

    - name: Test
      run: go test -v ./...
    
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: $binary
        path: ./
        
  release-content:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Download Artifact'
      uses: actions/download-artifact@v3
      with:
        name: $binary
    - name: Set permissions
      run: chmod +x $binary && sha256sum $binary && ls -al
    - name: 'Create GitHub Release'
      id: create-new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.${{github.run_number}}
        release_name: v0.0.${{github.run_number}}
    - name: Upload asset to Github Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: $binary
        asset_name: $binary
        asset_content_type: application/zip 
