# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: CGO_ENABLED=0 go build -o github-utility.bin -v ./... && chmod +x github-utility.bin && sha256sum github-utility.bin && ls -al

    - name: Test
      run: go test -v ./...
    
    - name: Upload 
      uses: actions/upload-artifact@v3
      with:
        name: github-utility
        path: ./github-utility
        
  release-content:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Download Artifact'
      uses: actions/download-artifact@v3
      with:
        name: github-utility
